services:
  nyt-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nyt_scraper_container
    
    environment:
      - PYTHONPATH=/app:/app/src
    
    shm_size: '2gb'
    
    volumes:
      - ./output:/app/output
      - ./config:/app/config  
      
    restart: "no"